theme = "rose_pine"

[editor]
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false
git-global = false
git-exclude = false

### colemak-dh bindings ###

[keys.normal]
m = "move_char_left"
M = "join_selections"
n = "move_visual_line_down"
N = "half_page_down"
e = "move_visual_line_up"
E = "half_page_up"
i = "move_char_right"
I = "keep_primary_selection" 

j = "keep_primary_selection"
J = "search" # todo
l = "move_next_word_end"
L = "move_next_long_word_end"
k = "search_next"
K = "search_prev"
h = "insert_mode"
H = "insert_at_line_start"

"ret" = "command_mode"


# match mode
[keys.normal.","]
m = "match_brackets"
s = "surround_add"
r = "surround_replace"
d = "surround_delete"
a = "select_textobject_around"
i = "select_textobject_inner"

# goto mode
[keys.normal.g]
m = "goto_line_start"
n = "move_line_down"
e = "move_line_up"
i = "goto_line_end"
"," = "goto_last_modified_file"
G = "goto_last_line"
k = "goto_next_buffer"
h = "goto_implementation"

# view mode
[keys.normal.z]
n = "scroll_down"
e = "scroll_up"

# window mode
[keys.normal.space.w]
m = "jump_view_left"
n = "jump_view_down"
e = "jump_view_up"
i = "jump_view_right"
M = "swap_view_left"
N = "swap_view_down"
E = "swap_view_up"
I = "swap_view_right"

# space mode
[keys.normal.space]
n = "file_picker_in_current_directory"

# unimpaired mode
[keys.normal.esc]
d = "goto_prev_diag"
D = "goto_first_diag"
f = "goto_prev_function"
t = "goto_prev_class"
a = "goto_prev_parameter"
c = "goto_prev_comment"
T = "goto_prev_test"
p = "goto_prev_paragraph"
g = "goto_prev_change"
G = "goto_first_change"
space = "add_newline_above"

[keys.normal."'"]
d = "goto_next_diag"
D = "goto_last_diag"
f = "goto_next_function"
t = "goto_next_class"
a = "goto_next_parameter"
c = "goto_next_comment"
T = "goto_next_test"
p = "goto_next_paragraph"
g = "goto_next_change"
G = "goto_last_change"
space = "add_newline_below"
