import = ["/home/rg/.config/alacritty/rose-pine.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "alacritty"

[font]
size = {{alacritty.font_size}}

[font.italic]
family = "Cartograph CF"
style = "Italic"

[font.normal]
family = "monospace"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Minus"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "E"
mods = "Alt"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
opacity = {{alacritty.opacity}}
