game:
  args: --locale=en_US --launch-product=league_of_legends --launch-patchline=live
  exe: /home/rg/Games/league-of-legends/drive_c/Riot Games/Riot Client/RiotClientServices.exe
  prefix: /home/rg/Games/league-of-legends
system:
  env:
    DXVK_LOG_LEVEL: none
    DXVK_STATE_CACHE_PATH: /home/rg/Games/league-of-legends
    STAGING_SHARED_MEMORY: '1'
    WINE_LARGE_ADDRESS_AWARE: '1'
    __GL_SHADER_DISK_CACHE: '1'
    __GL_SHADER_DISK_CACHE_PATH: /home/rg/Games/league-of-legends
wine:
  MouseWarpOverride: enable
  version: lutris-ge-lol-7.14-1-x86_64
