[helpers]

[x11.files]
".xinitrc" = "~/.xinitrc"

[x11.variables]
x11.enable = true

[wallpapers.files]
"kanehira_colors.jpg" = { target = "~/Pictures/Wallpapers/kanehira_colors.jpg", type = "symbolic"}
"kanehira_evening.jpg" = { target = "~/Pictures/Wallpapers/kanehira_evening.jpg", type = "symbolic"}

[scripts.files]
scripts = "~/.scripts"

[alacritty.files]
"config/alacritty" = "~/.config/alacritty"

[alacritty.variables]
alacritty.font_size = 20
alacritty.opacity = 0.95

[hypr.files]
"config/hypr" = "~/.config/hypr"

[eww.files]
"config/eww" = "~/.config/eww"

[zsh.files]
"config/zsh" = "~/.config/zsh"
".zshenv" = "~/.zshenv"

[btop.files]
"config/btop" = "~/.config/btop"

[colors.variables]
color.base = "#191724"
color.surface = "#1f1d2e"
color.overlay = "#26233a"
color.muted = "#6e6a86"
color.subtle = "#908caa"
color.text = "#e0def4"
color.love = "#eb6f92"
color.gold = "#f6c177"
color.rose = "#ebbcba"
color.pine = "#31748f"
color.foam = "#9ccfd8"
color.iris = "#c4a7e7"
color.hllow = "#21202e"
color.hlmed = "#403d52"
color.hlhi = "#524f67"
color.intel_blue = "#0071c5"
color.amd_red = "#ed1c24"

[fontconfig.files]
"config/fontconfig" = "~/.config/fontconfig"

[git.files]
"config/git" = "~/.config/git"

[mpd.files]
"config/mpd" = "~/.config/mpd"

[nvim.files]
"config/nvim" = "~/.config/nvim"

[vifm.files]
"config/vifm" = "~/.config/vifm"
"config/vifm/vifm-help.txt" = { target = "~/.config/vifm/vifm-help.txt", type = "symbolic" }

[wofi.files]
"config/wofi" = "~/.config/wofi"

[zathura.files]
"config/zathura" = '~/.config/zathura'

[ncmpcpp.files]
"config/ncmpcpp" = '~/.config/ncmpcpp'
"config/ncmpcpp/config" = { target = "~/.config/ncmpcpp/config", type = "symbolic" }

[wired.files]
"config/wired/wired.ron" = '~/.config/wired/wired.ron'

[desktop_entries.files]
"config/desktop_entries" = '~/.local/share/applications'

[newsboat.files]
"config/newsboat" = "~/.config/newsboat"

[fish.files]
"config/fish" = "~/.config/fish"
