[helpers]

[x11.files]
".xinitrc" = "~/.xinitrc"

[x11.variables]
x11.enable = true

[wallpapers.files]
"wall.png" = "~/Pictures/Wallpapers/wall.png"

[scripts.files]
scripts = "~/.scripts"

[zsh.files]
"config/zsh" = "~/.config/zsh"
".zshenv" = "~/.zshenv"

[btop.files]
"config/btop" = "~/.config/btop"

[fontconfig.files]
"config/fontconfig" = "~/.config/fontconfig"

[gammastep.files]
"config/gammastep" = "~/.config/gammastep"

[gammastep.variables]
gammastep.temp-day = 4500
gammastep.temp-night = 3200

[git.files]
"config/git" = "~/.config/git"

[mpd.files]
"config/mpd" = "~/.config/mpd"

[nvim.files]
"config/nvim" = "~/.config/nvim"

[sway.files]
"config/sway" = "~/.config/sway"

[swaylock.files]
"config/swaylock" = "~/.config/swaylock"

[vifm.files]
"config/vifm" = "~/.config/vifm"
"config/vifm/vifm-help.txt" = { target = "~/.config/vifm/vifm-help.txt", type = "symbolic" }

[waybar.files]
"config/waybar" = "~/.config/waybar"

[waybar.variables]
waybar.fontsize = 24
waybar.battery = false

[[waybar.variables.apps]]
binary = "teams" 
selector = "'[class=\"Microsoft Teams - Preview\"]'"
workspace = 10 
key = 't'

[[waybar.variables.apps]]
binary = "discord"
selector = "'[class=\"discord\"]'"
workspace = 9
key = 'd' 

[[waybar.variables.apps]]
binary = "spotify"
selector = "'[class=\"Spotify\"]'"
workspace = 8
key = 's'

[[waybar.variables.apps]]
# using apostrophes to make launch script threat it as a single argument
binary = "'alacritty --class vimpc -e vimpc'"
selector = "'[app_id=\"vimpc\"]'"
workspace = 7
key = 'm'

[[waybar.variables.apps]]
binary = "firefox"
selector = "'[class=\"firefox\"]'"
workspace = 6
key = 'w'

[[waybar.variables.apps]]
binary = "krita"
selector = "'[class=\"krita\"]'"
workspace = 5
key = 'k'

[wofi.files]
"config/wofi" = "~/.config/wofi"

[xkb.files]
"config/xkb" = "~/.config/xkb"

[zathura.files]
"config/zathura" = '~/.config/zathura'
