[helpers]

[x11.files]
".xinitrc" = "~/.xinitrc"

[x11.variables]
x11.enable = true

[wallpapers.files]
"wall.png" = { target = "~/Pictures/Wallpapers/wall.png", type = "symbolic"}

[scripts.files]
scripts = "~/.scripts"
"scripts/plsdo" = { target = "~/.scripts/plsdo", type = "symbolic" }

[alacritty.files]
"config/alacritty" = "~/.config/alacritty"

[alacritty.variables]
alacritty.font_size = 20
alacritty.opacity = 0.95

[zsh.files]
"config/zsh" = "~/.config/zsh"
".zshenv" = "~/.zshenv"

[btop.files]
"config/btop" = "~/.config/btop"

[colors.variables]
color.base = "#191724"
color.surface = "#1f1d2e"
color.overlay = "#26233a"
color.muted = "#6e6a86"
color.subtle = "#908caa"
color.text = "#e0def4"
color.love = "#eb6f92"
color.gold = "#f6c177"
color.rose = "#ebbcba"
color.pine = "#31748f"
color.foam = "#9ccfd8"
color.iris = "#c4a7e7"
color.hllow = "#21202e"
color.hlmed = "#403d52"
color.hlhi = "#524f67"
color.intel_blue = "#0071c5"
color.amd_red = "#ed1c24"

[fontconfig.files]
"config/fontconfig" = "~/.config/fontconfig"

[gammastep.files]
"config/gammastep" = "~/.config/gammastep"

[gammastep.variables]
gammastep.temp-day = 4500
gammastep.temp-night = 3200

[git.files]
"config/git" = "~/.config/git"

[mpd.files]
"config/mpd" = "~/.config/mpd"

[nvim.files]
"config/nvim" = "~/.config/nvim"

[sway.files]
"config/sway" = "~/.config/sway"

[swaylock.files]
"config/swaylock" = "~/.config/swaylock"

[vifm.files]
"config/vifm" = "~/.config/vifm"
"config/vifm/vifm-help.txt" = { target = "~/.config/vifm/vifm-help.txt", type = "symbolic" }

[waybar.files]
"config/waybar" = "~/.config/waybar"

[waybar.variables]
waybar.fontsize = 21

[[waybar.variables.apps]]
binary = "teams" 
selector = "'[class=\"Microsoft Teams - Preview\"]'"
workspace = 10 
key = 't'

[[waybar.variables.apps]]
binary = "discord"
selector = "'[class=\"discord\"]'"
workspace = 9
key = 'd' 

[[waybar.variables.apps]]
binary = "spotify"
selector = "'[class=\"Spotify\"]'"
workspace = 8
key = 's'

[[waybar.variables.apps]]
# using apostrophes to make launch script threat it as a single argument
binary = "'alacritty --class vimpc -e vimpc'"
selector = "'[app_id=\"vimpc\"]'"
workspace = 7
key = 'm'

[[waybar.variables.apps]]
binary = "firefox"
selector = "'[class=\"firefox\"]'"
workspace = 6
key = 'w'

[[waybar.variables.apps]]
binary = "krita"
selector = "'[class=\"krita\"]'"
workspace = 5
key = 'k'

[wofi.files]
"config/wofi" = "~/.config/wofi"

[xkb.files]
"config/xkb" = "~/.config/xkb"

[zathura.files]
"config/zathura" = '~/.config/zathura'

[ncmpcpp.files]
"config/ncmpcpp" = '~/.config/ncmpcpp'
"config/ncmpcpp/config" = { target = "~/.config/ncmpcpp/config", type = "symbolic" }

[river.files]
"config/river/init" = '~/.config/river/init'

[kanshi.files]
"config/kanshi/config" = '~/.config/kanshi/config'
