[[mgr.prepend_keymap]]
on = "Y"
run = "plugin toggle-pane min-preview"
desc = "Hide or show preview"

[[mgr.prepend_keymap]]
on = ["c", "a"]
run = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Close"
