[mgr]
sort_by = "natural"
sort_translit = true
linemode = "permissions"

[plugin]
prepend_previewers = [{ name = "*.md", run = "glow" }]

[opener]
rnote = [{ run = 'rnote "$@"', orphan = true, for = "unix" }]

[open]
prepend_rules = [{ name = "*.rnote", use = "rnote" }]
